baseURL = "https://arbeit-von-zu.haus/"
languageCode = "de-de"
title = "Arbeit von Zuhause"
theme = "chunky-poster"

[params]
  description = "Eine Sammlung von Ressourcen für Arbeitnehmer und Arbeitgeber."
  homepageImage = "/images/undraw_remotely.svg"

  [params.social]
    rss = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Zuhaus"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "Über uns"
    url = "/about/"
    weight = 0
