name: Build Web Page

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout with submodules, because we want to have a theme
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Yarn page
        run: yarn run generate

      - name: Deploy to gh pages
        # only deploy if we are on the source branch
        if: github.ref == 'refs/heads/source'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: master
          cname: arbeit-von-zu.haus
