name: Build Web Page

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout with submodules, because we want to have a theme
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.67.1'

      - name: Build Hugo page
        run: hugo --minify --buildDrafts

      - name: Deploy to gh pages
        # only deploy if we are on the source branch
        if: github.ref == 'refs/heads/source'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          cname: arbeit-von-zu.haus
